import type { Dictionary } from './en';

const bs: Dictionary = {
  'app.name': 'Kazivanja o poslanicima',

  'common.continue': 'Nastavi',
  'common.back': 'Nazad',
  'common.cancel': 'Odustani',
  'common.start': 'Počni',
  'common.done': 'Gotovo',
  'common.check': 'Provjeri',
  'common.retry': 'Pokušaj ponovo',
  'common.locked': 'Zaključano',
  'common.level': 'Nivo {level}',
  'common.sources': 'Izvori',
  'common.scholarsDiffer': 'Učenjaci se razilaze',
  'common.save': 'Sačuvaj',

  'tabs.home': 'Početna',
  'tabs.map': 'Kazivanja',
  'tabs.review': 'Ponavljanje',
  'tabs.profile': 'Napredak',

  'honorific.alayhis-salam': 'a.s.',
  'honorific.sallallahu-alayhi-wa-sallam': 's.a.v.s.',

  'onboarding.title': 'Kazivanja o poslanicima',
  'onboarding.subtitle': 'Interaktivna kazivanja iz Kur\'ana – kroz mjesta, predmete i odluke. Poslanici se nikada ne prikazuju na slikama.',
  'onboarding.language': 'Izaberi jezik',
  'onboarding.name': 'Kako se zoveš?',
  'onboarding.namePlaceholder': 'Tvoje ime',
  'onboarding.nameHint': 'Tvoje ime ostaje samo na ovom uređaju.',
  'onboarding.nameError': 'Unesi ime (1–20 znakova).',
  'onboarding.start': 'Započni putovanje',

  'home.greeting': 'Es-selamu alejkum, {name}!',
  'home.subtitle': 'Koje ćeš kazivanje danas istražiti?',
  'home.continue': 'Nastavi kazivanje',
  'home.continueStep': 'Korak {current} od {total}',
  'home.startNext': 'Sljedeće kazivanje',
  'home.allDone': 'Završio si sva kazivanja. Divno!',
  'home.featured': 'Kazivanje dana',
  'home.progress': 'Tvoj napredak',
  'home.daily': 'Pitanje dana',
  'home.dailyDone': 'Odgovoreno danas – vidimo se sutra!',
  'home.dailyNone': 'Započni prvo kazivanje da otključaš pitanja dana.',
  'home.recent': 'Nedavno završeno',
  'home.recentEmpty': 'Završena kazivanja pojavit će se ovdje.',

  'progress.stories': 'Kazivanja',
  'progress.scenes': 'Scene',
  'progress.lessons': 'Naučene pouke',
  'progress.quiz': 'Prosječan rezultat',
  'progress.reviews': 'Zapamćena ponavljanja',
  'progress.answers': 'Tačni odgovori',

  'map.title': 'Mapa kazivanja',
  'map.subtitle': 'Putuj redom kroz kazivanja o poslanicima.',
  'map.lockedBecause': 'Prvo završi kazivanje o: {name}.',
  'map.completed': 'Završeno',
  'map.inProgress': 'Započeto',

  'story.overview': 'O ovom kazivanju',
  'story.scenes': '{count} scene',
  'story.lessons': 'Šta ćeš naučiti',
  'story.start': 'Počni kazivanje',
  'story.resume': 'Nastavi kazivanje',
  'story.replay': 'Pročitaj ponovo',
  'story.notFound': 'Ovo kazivanje nije pronađeno.',
  'story.place': 'Mjesto',
  'story.symbolNote': 'Poslanici se nikada ne prikazuju. Slike pokazuju samo mjesta i predmete.',

  'player.exitTitle': 'Pauzirati kazivanje?',
  'player.exitBody': 'Tvoje mjesto je sačuvano. Kazivanje možeš nastaviti kasnije.',
  'player.exit': 'Pauziraj',
  'player.stay': 'Nastavi čitati',
  'player.intro': 'Uvod',
  'player.scene': 'Scena {number}',
  'player.role.interaction': 'Šta misliš, šta se desilo?',
  'player.role.question': 'Pitanje',
  'player.role.miniGame': 'Mini igra',
  'player.role.quiz': 'Kviz znanja',
  'player.correct': 'Tačno!',
  'player.notQuite': 'Ne baš',
  'player.correctAnswer': 'Tačan odgovor: {answer}',
  'player.addedToReview': 'Ovo pitanje ćemo kasnije ponoviti.',
  'player.lessonsTitle': 'Šta smo naučili?',
  'player.example': 'Na primjer',
  'player.reflection': 'Razmisli',
  'player.lessonsDone': 'Razmislio sam',

  'q.true': 'Tačno',
  'q.false': 'Netačno',
  'q.ordering.hint': 'Dodirni događaje pravilnim redom.',
  'q.ordering.reset': 'Počni ispočetka',
  'q.matching.hint': 'Dodirni stavku lijevo, pa njen par desno.',
  'q.matching.mistakes': 'Greške: {count}',
  'q.memory.hint': 'Okreni dvije karte da pronađeš par.',
  'q.memory.moves': 'Potezi: {count}',
  'q.find.hint': 'Dodirni sve predmete koji pripadaju kazivanju, pa provjeri.',
  'q.find.selected': 'Odabrano: {count}',
  'q.map.hint': 'Dodirni mjesto na mapi.',
  'q.lessonChoice.title': 'Izaberi tačnu pouku',
  'q.scenario.title': 'Odluka',

  'place.makkah': 'Mekka',
  'place.madinah': 'Medina',
  'place.egypt': 'Egipat (Nil)',
  'place.jerusalem': 'Bejtul-Makdis',
  'place.judi': 'Džudi',
  'place.mesopotamia': 'Mezopotamija',

  'reward.title': 'Kazivanje završeno!',
  'reward.score': '{correct} od {total} tačno',
  'reward.lines.storyComplete': 'Kazivanje završeno',
  'reward.lines.perfectBonus': 'Bonus za bez greške',
  'reward.lines.learning': 'Odgovori i pouke',
  'reward.noXp': 'XP za ovo kazivanje si već osvojio – ponovno čitanje ti ipak pomaže da zapamtiš!',
  'reward.next': 'Sljedeće kazivanje',
  'reward.map': 'Nazad na mapu',
  'reward.review': 'Ponovi greške',
  'reward.lessons': 'Naučene pouke',

  'review.title': 'Ponavljanje',
  'review.subtitle': 'Teža pitanja vraćaju se u pravo vrijeme.',
  'review.start': 'Počni ponavljanje ({count})',
  'review.emptyTitle': 'Trenutno nema ništa za ponavljanje',
  'review.emptyBody': 'Kada netačno odgovoriš na pitanje, ono će se kasnije vratiti ovdje.',
  'review.next': 'Sljedeće ponavljanje: {date}',
  'review.doneTitle': 'Ponavljanje završeno',
  'review.doneBody': 'Zapamtio si {correct} od {total}. Iz grešaka učimo!',
  'review.pending': 'Pitanja na listi za ponavljanje: {count}',

  'daily.title': 'Pitanje dana',
  'daily.doneTitle': 'Bravo!',
  'daily.already': 'Na današnje pitanje si već odgovorio. Sutra stiže novo!',

  'profile.title': 'Tvoj napredak',
  'profile.xpToNext': 'Još {xp} XP do nivoa {level}',
  'profile.badges': 'Značke',
  'profile.settings': 'Postavke',
  'badges.locked': 'Još nije osvojena',
  'badges.earnedOn': 'Osvojena {date}',
  'badge.story_explorer.name': 'Istraživač kazivanja',
  'badge.story_explorer.desc': 'Završi svoje prvo kazivanje.',
  'badge.history_learner.name': 'Poznavalac historije',
  'badge.history_learner.desc': 'Završi četiri kazivanja.',
  'badge.prophet_explorer.name': 'Istraživač poslanika',
  'badge.prophet_explorer.desc': 'Završi svih osam kazivanja.',
  'badge.sabr_champion.name': 'Šampion sabura',
  'badge.sabr_champion.desc': 'Nauči sve pouke o saburu (strpljenju).',
  'badge.knowledge_seeker.name': 'Tragač za znanjem',
  'badge.knowledge_seeker.desc': 'Tačno odgovori na 50 pitanja.',
  'badge.perfect_story.name': 'Kazivanje bez greške',
  'badge.perfect_story.desc': 'Završi kazivanje bez ijedne greške.',
  'badge.review_master.name': 'Majstor ponavljanja',
  'badge.review_master.desc': 'Zapamti 10 pitanja u ponavljanju.',
  'badge.daily_learner.name': 'Svakodnevni učenik',
  'badge.daily_learner.desc': 'Odgovori na 5 pitanja dana.',
  'celebrate.badge': 'Nova značka otključana!',
  'celebrate.levelTitle': 'Novi nivo!',
  'celebrate.levelBody': 'Dostigao si nivo {level}. Nastavi istraživati!',

  'settings.title': 'Postavke',
  'settings.general': 'Općenito',
  'settings.language': 'Jezik',
  'settings.name': 'Ime',
  'settings.sound': 'Zvučni efekti',
  'settings.haptics': 'Vibracija',
  'settings.accessibility': 'Pristupačnost',
  'settings.largeText': 'Veći tekst',
  'settings.reducedMotion': 'Smanji animacije',
  'settings.info': 'Informacije',
  'settings.about': 'O aplikaciji',
  'settings.privacy': 'Privatnost',
  'settings.sources': 'Izvori',
  'settings.data': 'Podaci',
  'settings.reset': 'Poništi napredak',
  'settings.resetDesc': 'Briše sav napredak, XP i značke na ovom uređaju.',
  'settings.resetTitle': 'Poništiti sav napredak?',
  'settings.resetBody': 'Ovo se ne može vratiti.',
  'settings.resetConfirm': 'Da, poništi',
  'settings.version': 'Verzija {version}',

  'about.title': 'O aplikaciji',
  'about.p1': 'Kazivanja o poslanicima je besplatna igra-slikovnica bez interneta koja djecu uči kazivanjima o poslanicima onako kako ih prenosi Kur\'an – kroz scene, odluke, mini igre i razmišljanje.',
  'about.p2': 'Nema reklama, kupovina, pretplata ni korisničkih računa.',
  'about.p3': 'Aplikacija je pomoćnik u učenju. Ne zamjenjuje roditelje, učitelje niti čitanje Kur\'ana i njegovog tumačenja s kvalifikovanim učenjacima.',
  'privacy.title': 'Privatnost',
  'privacy.p1': 'Aplikacija ne prikuplja lične podatke i nema reklama, analitike ni praćenja. Ne koristi internet.',
  'privacy.p2': 'Tvoje ime i napredak čuvaju se samo na ovom uređaju i mogu se obrisati opcijom „Poništi napredak“.',
  'sources.title': 'Izvori',
  'sources.p1': 'Svako kazivanje prepričano je iz Kur\'ana; sura i ajet navedeni su uz svaku scenu i pitanje. Nekoliko detalja potiče iz vjerodostojnog sunneta (Sahih el-Buhari) i klasične biografije Poslanika ﷺ od Ibn Hišama.',
  'sources.p2': 'Nijedan dijalog nije izmišljen i nijedan događaj dodan. Gdje Kur\'an nekoga citira, aplikacija jednostavnim riječima opisuje značenje i navodi ajet.',
  'sources.p3': 'Poslanici se nikada ne prikazuju. Scene prikazuju samo pejzaže, građevine, vrijeme i predmete.',

  'error.title': 'Nešto nije u redu',
  'error.body': 'Tvoj napredak je siguran. Pokušaj ponovo.',
  'notFound.title': 'Stranica nije pronađena',
  'notFound.home': 'Na početnu',

  'a11y.back': 'Nazad',
  'a11y.close': 'Pauziraj kazivanje',
  'a11y.progress': 'Napredak {percent} posto',
  'a11y.xpBar': '{xp} od {total} XP do sljedećeg nivoa',
  'a11y.stars': '{count} od 3 zvjezdice',
  'a11y.selected': 'odabrano',
  'a11y.correct': 'tačno',
  'a11y.incorrect': 'netačno',
  'a11y.card': 'Karta {index}',
  'a11y.hiddenCard': 'Skrivena karta {index}',
};

export default bs;
