import type { Dictionary } from './en';

const de: Dictionary = {
  'app.name': 'Geschichten der Propheten',

  'common.continue': 'Weiter',
  'common.back': 'Zurück',
  'common.cancel': 'Abbrechen',
  'common.start': 'Starten',
  'common.done': 'Fertig',
  'common.check': 'Prüfen',
  'common.retry': 'Nochmal versuchen',
  'common.locked': 'Gesperrt',
  'common.level': 'Stufe {level}',
  'common.sources': 'Quellen',
  'common.scholarsDiffer': 'Gelehrte sind sich uneinig',
  'common.save': 'Speichern',

  'tabs.home': 'Start',
  'tabs.map': 'Geschichten',
  'tabs.review': 'Wiederholen',
  'tabs.profile': 'Fortschritt',

  'honorific.alayhis-salam': 'Friede sei mit ihm',
  'honorific.sallallahu-alayhi-wa-sallam': 'Allahs Segen und Frieden seien auf ihm',

  'onboarding.title': 'Geschichten der Propheten',
  'onboarding.subtitle': 'Interaktive Geschichten aus dem Koran – erzählt durch Orte, Gegenstände und Entscheidungen. Propheten werden nie bildlich gezeigt.',
  'onboarding.language': 'Wähle deine Sprache',
  'onboarding.name': 'Wie heißt du?',
  'onboarding.namePlaceholder': 'Dein Name',
  'onboarding.nameHint': 'Dein Name bleibt nur auf diesem Gerät.',
  'onboarding.nameError': 'Bitte gib einen Namen ein (1–20 Zeichen).',
  'onboarding.start': 'Die Reise beginnen',

  'home.greeting': 'As-salamu alaikum, {name}!',
  'home.subtitle': 'Welche Geschichte entdeckst du heute?',
  'home.continue': 'Geschichte fortsetzen',
  'home.continueStep': 'Schritt {current} von {total}',
  'home.startNext': 'Nächste Geschichte',
  'home.allDone': 'Du hast alle Geschichten abgeschlossen. Wunderbar!',
  'home.featured': 'Geschichte des Tages',
  'home.progress': 'Dein Fortschritt',
  'home.daily': 'Frage des Tages',
  'home.dailyDone': 'Heute beantwortet – bis morgen!',
  'home.dailyNone': 'Beginne deine erste Geschichte, um tägliche Fragen freizuschalten.',
  'home.recent': 'Zuletzt abgeschlossen',
  'home.recentEmpty': 'Abgeschlossene Geschichten erscheinen hier.',

  'progress.stories': 'Geschichten',
  'progress.scenes': 'Szenen',
  'progress.lessons': 'Gelernte Lehren',
  'progress.quiz': 'Durchschnittliche Punktzahl',
  'progress.reviews': 'Gemerkte Wiederholungen',
  'progress.answers': 'Richtige Antworten',

  'map.title': 'Geschichtenkarte',
  'map.subtitle': 'Reise der Reihe nach durch die Geschichten der Propheten.',
  'map.lockedBecause': 'Schließe zuerst die Geschichte von {name} ab.',
  'map.completed': 'Abgeschlossen',
  'map.inProgress': 'Begonnen',

  'story.overview': 'Über diese Geschichte',
  'story.scenes': '{count} Szenen',
  'story.lessons': 'Was du lernen wirst',
  'story.start': 'Geschichte starten',
  'story.resume': 'Geschichte fortsetzen',
  'story.replay': 'Nochmal lesen',
  'story.notFound': 'Diese Geschichte wurde nicht gefunden.',
  'story.place': 'Ort',
  'story.symbolNote': 'Propheten werden nie gezeigt. Die Bilder zeigen nur Orte und Gegenstände.',

  'player.exitTitle': 'Geschichte pausieren?',
  'player.exitBody': 'Deine Stelle ist gespeichert. Du kannst die Geschichte später fortsetzen.',
  'player.exit': 'Pausieren',
  'player.stay': 'Weiterlesen',
  'player.intro': 'Einleitung',
  'player.scene': 'Szene {number}',
  'player.role.interaction': 'Was denkst du, geschah dann?',
  'player.role.question': 'Frage',
  'player.role.miniGame': 'Minispiel',
  'player.role.quiz': 'Wissensquiz',
  'player.correct': 'Richtig!',
  'player.notQuite': 'Nicht ganz',
  'player.correctAnswer': 'Die richtige Antwort: {answer}',
  'player.addedToReview': 'Wir wiederholen diese Frage später noch einmal.',
  'player.lessonsTitle': 'Was haben wir gelernt?',
  'player.example': 'Zum Beispiel',
  'player.reflection': 'Denk darüber nach',
  'player.lessonsDone': 'Ich habe darüber nachgedacht',

  'q.true': 'Richtig',
  'q.false': 'Falsch',
  'q.ordering.hint': 'Tippe die Ereignisse in der richtigen Reihenfolge an.',
  'q.ordering.reset': 'Neu beginnen',
  'q.matching.hint': 'Tippe links einen Eintrag an, dann seinen Partner rechts.',
  'q.matching.mistakes': 'Fehler: {count}',
  'q.memory.hint': 'Decke zwei Karten auf, um ein Paar zu finden.',
  'q.memory.moves': 'Züge: {count}',
  'q.find.hint': 'Tippe alle Gegenstände an, die zur Geschichte gehören, und prüfe dann.',
  'q.find.selected': '{count} ausgewählt',
  'q.map.hint': 'Tippe auf einen Ort auf der Karte.',
  'q.lessonChoice.title': 'Wähle die richtige Lehre',
  'q.scenario.title': 'Entscheidung',

  'place.makkah': 'Mekka',
  'place.madinah': 'Medina',
  'place.egypt': 'Ägypten (Nil)',
  'place.jerusalem': 'Bait al-Maqdis',
  'place.judi': 'Al-Dschudi',
  'place.mesopotamia': 'Mesopotamien',

  'reward.title': 'Geschichte geschafft!',
  'reward.score': '{correct} von {total} richtig',
  'reward.lines.storyComplete': 'Geschichte abgeschlossen',
  'reward.lines.perfectBonus': 'Bonus für fehlerfrei',
  'reward.lines.learning': 'Antworten und Lehren',
  'reward.noXp': 'Die XP für diese Geschichte hast du schon verdient – erneutes Lesen hilft dir trotzdem beim Merken!',
  'reward.next': 'Nächste Geschichte',
  'reward.map': 'Zurück zur Karte',
  'reward.review': 'Meine Fehler wiederholen',
  'reward.lessons': 'Gelernte Lehren',

  'review.title': 'Wiederholen',
  'review.subtitle': 'Knifflige Fragen kommen zur richtigen Zeit wieder.',
  'review.start': 'Wiederholung starten ({count})',
  'review.emptyTitle': 'Gerade gibt es nichts zu wiederholen',
  'review.emptyBody': 'Wenn du eine Frage falsch beantwortest, kommt sie später hierher zurück.',
  'review.next': 'Nächste Wiederholung: {date}',
  'review.doneTitle': 'Wiederholung geschafft',
  'review.doneBody': 'Du hast dir {correct} von {total} gemerkt. Aus Fehlern lernen wir!',
  'review.pending': '{count} Fragen auf deiner Wiederholungsliste',

  'daily.title': 'Frage des Tages',
  'daily.doneTitle': 'Gut gemacht!',
  'daily.already': 'Du hast die heutige Frage schon beantwortet. Morgen kommt eine neue!',

  'profile.title': 'Dein Fortschritt',
  'profile.xpToNext': 'Noch {xp} XP bis Stufe {level}',
  'profile.badges': 'Abzeichen',
  'profile.settings': 'Einstellungen',
  'badges.locked': 'Noch nicht verdient',
  'badges.earnedOn': 'Verdient am {date}',
  'badge.story_explorer.name': 'Geschichten-Entdecker',
  'badge.story_explorer.desc': 'Schließe deine erste Geschichte ab.',
  'badge.history_learner.name': 'Geschichtskenner',
  'badge.history_learner.desc': 'Schließe vier Geschichten ab.',
  'badge.prophet_explorer.name': 'Propheten-Entdecker',
  'badge.prophet_explorer.desc': 'Schließe alle acht Geschichten ab.',
  'badge.sabr_champion.name': 'Sabr-Champion',
  'badge.sabr_champion.desc': 'Lerne alle Lehren über Sabr (Geduld).',
  'badge.knowledge_seeker.name': 'Wissenssucher',
  'badge.knowledge_seeker.desc': 'Beantworte 50 Fragen richtig.',
  'badge.perfect_story.name': 'Fehlerfreie Geschichte',
  'badge.perfect_story.desc': 'Schließe eine Geschichte ohne Fehler ab.',
  'badge.review_master.name': 'Wiederholungs-Meister',
  'badge.review_master.desc': 'Merke dir 10 Fragen in der Wiederholung.',
  'badge.daily_learner.name': 'Täglich dabei',
  'badge.daily_learner.desc': 'Beantworte 5 Fragen des Tages.',
  'celebrate.badge': 'Neues Abzeichen freigeschaltet!',
  'celebrate.levelTitle': 'Aufgestiegen!',
  'celebrate.levelBody': 'Du hast Stufe {level} erreicht. Entdecke weiter!',

  'settings.title': 'Einstellungen',
  'settings.general': 'Allgemein',
  'settings.language': 'Sprache',
  'settings.name': 'Name',
  'settings.sound': 'Soundeffekte',
  'settings.haptics': 'Vibration',
  'settings.accessibility': 'Barrierefreiheit',
  'settings.largeText': 'Größere Schrift',
  'settings.reducedMotion': 'Bewegung reduzieren',
  'settings.info': 'Informationen',
  'settings.about': 'Über die App',
  'settings.privacy': 'Datenschutz',
  'settings.sources': 'Quellen',
  'settings.data': 'Daten',
  'settings.reset': 'Fortschritt zurücksetzen',
  'settings.resetDesc': 'Löscht allen Fortschritt, XP und Abzeichen auf diesem Gerät.',
  'settings.resetTitle': 'Gesamten Fortschritt zurücksetzen?',
  'settings.resetBody': 'Das kann nicht rückgängig gemacht werden.',
  'settings.resetConfirm': 'Ja, zurücksetzen',
  'settings.version': 'Version {version}',

  'about.title': 'Über die App',
  'about.p1': 'Geschichten der Propheten ist ein kostenloses Offline-Geschichtenspiel, das Kindern die Geschichten der Propheten so vermittelt, wie der Koran sie erzählt – durch Szenen, Entscheidungen, Minispiele und Nachdenken.',
  'about.p2': 'Es gibt keine Werbung, keine Käufe, keine Abos und keine Konten.',
  'about.p3': 'Die App ist ein Lernbegleiter. Sie ersetzt weder Eltern noch Lehrkräfte noch das Lesen des Korans und seiner Erklärung mit qualifizierten Gelehrten.',
  'privacy.title': 'Datenschutz',
  'privacy.p1': 'Die App sammelt keine persönlichen Daten und hat keine Werbung, Analyse oder Tracking. Sie nutzt kein Internet.',
  'privacy.p2': 'Dein Name und dein Fortschritt werden nur auf diesem Gerät gespeichert und können mit „Fortschritt zurücksetzen“ gelöscht werden.',
  'sources.title': 'Quellen',
  'sources.p1': 'Jede Geschichte wird aus dem Koran nacherzählt; Sure und Vers stehen bei jeder Szene und Frage. Einige Details stammen aus der authentischen Sunna (Sahih al-Bukhari) und der klassischen Prophetenbiografie von Ibn Hischam.',
  'sources.p2': 'Es werden keine Dialoge erfunden und keine Ereignisse hinzugefügt. Wo der Koran jemanden zitiert, beschreibt die App die Bedeutung in einfachen Worten und nennt den Vers.',
  'sources.p3': 'Propheten werden nie dargestellt. Die Szenen zeigen nur Landschaften, Bauwerke, Wetter und Gegenstände.',

  'error.title': 'Etwas ist schiefgelaufen',
  'error.body': 'Dein Fortschritt ist sicher. Bitte versuche es erneut.',
  'notFound.title': 'Seite nicht gefunden',
  'notFound.home': 'Zur Startseite',

  'a11y.back': 'Zurück',
  'a11y.close': 'Geschichte pausieren',
  'a11y.progress': 'Fortschritt {percent} Prozent',
  'a11y.xpBar': '{xp} von {total} XP bis zur nächsten Stufe',
  'a11y.stars': '{count} von 3 Sternen',
  'a11y.selected': 'ausgewählt',
  'a11y.correct': 'richtig',
  'a11y.incorrect': 'falsch',
  'a11y.card': 'Karte {index}',
  'a11y.hiddenCard': 'Verdeckte Karte {index}',
};

export default de;
