const en = {
  'app.name': 'Story of the Prophets',

  'common.continue': 'Continue',
  'common.back': 'Back',
  'common.cancel': 'Cancel',
  'common.start': 'Start',
  'common.done': 'Done',
  'common.check': 'Check',
  'common.retry': 'Try again',
  'common.locked': 'Locked',
  'common.level': 'Level {level}',
  'common.sources': 'Sources',
  'common.scholarsDiffer': 'Scholars differ',
  'common.save': 'Save',

  'tabs.home': 'Home',
  'tabs.map': 'Stories',
  'tabs.review': 'Review',
  'tabs.profile': 'Progress',

  'honorific.alayhis-salam': 'peace be upon him',
  'honorific.sallallahu-alayhi-wa-sallam': 'peace and blessings be upon him',

  'onboarding.title': 'Story of the Prophets',
  'onboarding.subtitle': 'Interactive stories from the Quran – told through places, objects and choices. Prophets are never shown in pictures.',
  'onboarding.language': 'Choose your language',
  'onboarding.name': 'What is your name?',
  'onboarding.namePlaceholder': 'Your name',
  'onboarding.nameHint': 'Your name stays only on this device.',
  'onboarding.nameError': 'Please enter a name (1–20 characters).',
  'onboarding.start': 'Begin the journey',

  'home.greeting': 'As-salamu alaykum, {name}!',
  'home.subtitle': 'Which story will you explore today?',
  'home.continue': 'Continue story',
  'home.continueStep': 'Step {current} of {total}',
  'home.startNext': 'Next story',
  'home.allDone': 'You have completed every story. Wonderful!',
  'home.featured': 'Featured story',
  'home.progress': 'Your progress',
  'home.daily': 'Daily question',
  'home.dailyDone': 'Answered today – come back tomorrow!',
  'home.dailyNone': 'Start your first story to unlock daily questions.',
  'home.recent': 'Recently completed',
  'home.recentEmpty': 'Completed stories will appear here.',

  'progress.stories': 'Stories',
  'progress.scenes': 'Scenes',
  'progress.lessons': 'Lessons learned',
  'progress.quiz': 'Average score',
  'progress.reviews': 'Reviews remembered',
  'progress.answers': 'Correct answers',

  'map.title': 'Story Map',
  'map.subtitle': 'Travel through the stories of the prophets in order.',
  'map.lockedBecause': 'Complete the story of {name} first.',
  'map.completed': 'Completed',
  'map.inProgress': 'In progress',

  'story.overview': 'About this story',
  'story.scenes': '{count} scenes',
  'story.lessons': 'What you will learn',
  'story.start': 'Start story',
  'story.resume': 'Continue story',
  'story.replay': 'Read again',
  'story.notFound': 'This story could not be found.',
  'story.place': 'Place',
  'story.symbolNote': 'Prophets are never shown. The pictures show only places and objects.',

  'player.exitTitle': 'Pause this story?',
  'player.exitBody': 'Your place is saved. You can continue the story later.',
  'player.exit': 'Pause',
  'player.stay': 'Keep reading',
  'player.intro': 'Introduction',
  'player.scene': 'Scene {number}',
  'player.role.interaction': 'What do you think happened next?',
  'player.role.question': 'Question',
  'player.role.miniGame': 'Mini game',
  'player.role.quiz': 'Knowledge quiz',
  'player.correct': 'Correct!',
  'player.notQuite': 'Not quite',
  'player.correctAnswer': 'The correct answer: {answer}',
  'player.addedToReview': 'We will review this question again later.',
  'player.lessonsTitle': 'What did we learn?',
  'player.example': 'For example',
  'player.reflection': 'Think about it',
  'player.lessonsDone': 'I have thought about it',

  'q.true': 'True',
  'q.false': 'False',
  'q.ordering.hint': 'Tap the events in the right order.',
  'q.ordering.reset': 'Start over',
  'q.matching.hint': 'Tap an item on the left, then its partner on the right.',
  'q.matching.mistakes': 'Mistakes: {count}',
  'q.memory.hint': 'Flip two cards to find a matching pair.',
  'q.memory.moves': 'Moves: {count}',
  'q.find.hint': 'Tap every object that belongs to the story, then check.',
  'q.find.selected': '{count} selected',
  'q.map.hint': 'Tap a place on the map.',
  'q.lessonChoice.title': 'Choose the correct lesson',
  'q.scenario.title': 'Decision',

  'place.makkah': 'Makkah',
  'place.madinah': 'Madinah',
  'place.egypt': 'Egypt (Nile)',
  'place.jerusalem': 'Bayt al-Maqdis',
  'place.judi': 'Al-Judi',
  'place.mesopotamia': 'Mesopotamia',

  'reward.title': 'Story complete!',
  'reward.score': '{correct} of {total} correct',
  'reward.lines.storyComplete': 'Story completed',
  'reward.lines.perfectBonus': 'Perfect score bonus',
  'reward.lines.learning': 'Answers and lessons',
  'reward.noXp': 'You already earned the XP for this story – reading it again still helps you remember!',
  'reward.next': 'Next story',
  'reward.map': 'Back to the map',
  'reward.review': 'Review my mistakes',
  'reward.lessons': 'Lessons learned',

  'review.title': 'Review',
  'review.subtitle': 'Questions you found tricky come back at the right time.',
  'review.start': 'Start review ({count})',
  'review.emptyTitle': 'Nothing to review right now',
  'review.emptyBody': 'When you answer a question wrongly, it will come back here later.',
  'review.next': 'Next review: {date}',
  'review.doneTitle': 'Review complete',
  'review.doneBody': 'You remembered {correct} of {total}. Mistakes are how we learn!',
  'review.pending': '{count} questions in your review list',

  'daily.title': 'Daily question',
  'daily.doneTitle': 'Well done!',
  'daily.already': 'You already answered today’s question. A new one comes tomorrow!',

  'profile.title': 'Your progress',
  'profile.xpToNext': '{xp} XP to level {level}',
  'profile.badges': 'Badges',
  'profile.settings': 'Settings',
  'badges.locked': 'Not earned yet',
  'badges.earnedOn': 'Earned on {date}',
  'badge.story_explorer.name': 'Story Explorer',
  'badge.story_explorer.desc': 'Complete your first story.',
  'badge.history_learner.name': 'History Learner',
  'badge.history_learner.desc': 'Complete four stories.',
  'badge.prophet_explorer.name': 'Prophet Explorer',
  'badge.prophet_explorer.desc': 'Complete all eight stories.',
  'badge.sabr_champion.name': 'Sabr Champion',
  'badge.sabr_champion.desc': 'Learn every lesson about sabr (patience).',
  'badge.knowledge_seeker.name': 'Knowledge Seeker',
  'badge.knowledge_seeker.desc': 'Answer 50 questions correctly.',
  'badge.perfect_story.name': 'Perfect Story',
  'badge.perfect_story.desc': 'Finish a story without a mistake.',
  'badge.review_master.name': 'Review Master',
  'badge.review_master.desc': 'Remember 10 questions in review.',
  'badge.daily_learner.name': 'Daily Learner',
  'badge.daily_learner.desc': 'Answer 5 daily questions.',
  'celebrate.badge': 'New badge unlocked!',
  'celebrate.levelTitle': 'Level up!',
  'celebrate.levelBody': 'You reached level {level}. Keep exploring!',

  'settings.title': 'Settings',
  'settings.general': 'General',
  'settings.language': 'Language',
  'settings.name': 'Name',
  'settings.sound': 'Sound effects',
  'settings.haptics': 'Vibration',
  'settings.accessibility': 'Accessibility',
  'settings.largeText': 'Larger text',
  'settings.reducedMotion': 'Reduce motion',
  'settings.info': 'Information',
  'settings.about': 'About',
  'settings.privacy': 'Privacy',
  'settings.sources': 'Sources',
  'settings.data': 'Data',
  'settings.reset': 'Reset progress',
  'settings.resetDesc': 'Deletes all progress, XP and badges on this device.',
  'settings.resetTitle': 'Reset all progress?',
  'settings.resetBody': 'This cannot be undone.',
  'settings.resetConfirm': 'Yes, reset',
  'settings.version': 'Version {version}',

  'about.title': 'About',
  'about.p1': 'Story of the Prophets is a free, offline storybook game that teaches children the stories of the prophets as told in the Quran – through scenes, choices, mini games and reflection.',
  'about.p2': 'There are no advertisements, purchases, subscriptions or accounts.',
  'about.p3': 'The app is a learning companion. It does not replace parents, teachers or reading the Quran and its explanation with qualified scholars.',
  'privacy.title': 'Privacy',
  'privacy.p1': 'The app collects no personal data and has no ads, analytics or tracking. It does not use the internet.',
  'privacy.p2': 'Your name and progress are stored only on this device and can be deleted with “Reset progress”.',
  'sources.title': 'Sources',
  'sources.p1': 'Every story is retold from the Quran, with surah and verse references shown on each scene and question. A few details come from the authentic Sunnah (Sahih al-Bukhari) and the classical biography of the Prophet ﷺ by Ibn Hisham.',
  'sources.p2': 'No dialogue is invented and no events are added. Where the Quran quotes someone, the app describes the meaning in simple words and cites the verse.',
  'sources.p3': 'Prophets are never depicted. Scenes show landscapes, architecture, weather and objects only.',

  'error.title': 'Something went wrong',
  'error.body': 'Your progress is safe. Please try again.',
  'notFound.title': 'Page not found',
  'notFound.home': 'Go home',

  'a11y.back': 'Go back',
  'a11y.close': 'Pause story',
  'a11y.progress': 'Progress {percent} percent',
  'a11y.xpBar': '{xp} of {total} XP towards the next level',
  'a11y.stars': '{count} of 3 stars',
  'a11y.selected': 'selected',
  'a11y.correct': 'correct',
  'a11y.incorrect': 'incorrect',
  'a11y.card': 'Card {index}',
  'a11y.hiddenCard': 'Hidden card {index}',
} as const;

export type TranslationKey = keyof typeof en;
export type Dictionary = Record<TranslationKey, string>;

export default en as Dictionary;
